### ISSUE TITLE
Getting error

### ISSUE THREAD

**Issue by yabasi** [Honvid/thrift-hbase-laravel#1]
Hi,
We are developing a laravel hbase project and wants to use this "thrift-hbase-laravel" library.
We are getting an error which is below that i attached as images.

NOTE: Is this library working? or are you still working on it ?

![error1](https://user-images.githubusercontent.com/2900493/41269351-7843d310-6e0d-11e8-9f7e-2fc0ad18873b.png)

![config-app](https://user-images.githubusercontent.com/2900493/41269396-a555dd62-6e0d-11e8-91d7-b747175c8278.png)

![config_folder](https://user-images.githubusercontent.com/2900493/41269482-0e9c4806-6e0e-11e8-885d-b791bb16a6f2.png)

and when we install library
`[test@host laravel] $ composer require honvid/thrift-hbase-laravel
Using version ^1.0 for honvid/thrift-hbase-laravel
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 2 installs, 0 updates, 0 removals
  - Installing apache/thrift (0.11.0): Loading from cache
  - Installing honvid/thrift-hbase-laravel (v1.0): Loading from cache
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover
Discovered Package: fideloper/proxy
Discovered Package: laravel/tinker
Discovered Package: nunomaduro/collision
Package manifest generated successfully.

[test@host laravel] $ php artisan vendor:publish --provider="Honvid\Providers\ThriftServiceProvider"
Copied File [/vendor/honvid/thrift-hbase-laravel/src/Config/thrift.php] To [/config/thrift.php]
Publishing complete.`

**Comment by Honvid** [comment]
thanks for install it. I'm working on it. 
Now it is worked. please try `composer update` again.

**Comment by Honvid** [comment]
sorry for that, I'm just working on it.
Now it fixed, please try composer update again, if do not work, waiting the package refresh. 
thanks for install it.
